### ISSUE TITLE
compile error on Ubuntu 11.10

### ISSUE THREAD

**Issue by wwkeyboard** [wedesoft/hornetseye-ffmpeg#1]
This is a fresh install, using ruby 1.9.3(installed with rvm) and installing all of the libraries mentioned on http://www.wedesoft.demon.co.uk/hornetseye-api/file.Installation.html#hornetseye-v4l2.  I'm going to try 1.9.2 after submitting this report to see if I get the same issues.

trace: 

gems/hornetseye-ffmpeg$ rake --trace
** Invoke .depends.mf (first_time, not_needed)
** Invoke config_h (first_time)
** Invoke ext/config.h (first_time, not_needed)
** Execute config_h
** Invoke default (first_time)
** Invoke all (first_time)
** Invoke ext/hornetseye_ffmpeg.so (first_time)
** Invoke ext/sequence.o (first_time, not_needed)
** Invoke ext/sequence.cc (first_time, not_needed)
** Invoke ext/sequence.hh (first_time, not_needed)
** Invoke ext/rubyinc.hh (first_time, not_needed)
** Invoke ext/avoutput.o (first_time)
** Invoke ext/avoutput.cc (first_time, not_needed)
** Invoke ext/avoutput.hh (first_time, not_needed)
** Invoke ext/rubyinc.hh (not_needed)
** Invoke ext/error.hh (first_time, not_needed)
** Invoke ext/frame.hh (first_time, not_needed)
** Invoke ext/sequence.hh (not_needed)
** Execute ext/avoutput.o
g++ -DNDEBUG -DHAVE_CONFIG_H -D__STDC_CONSTANT_MACROS  -D_FILE_OFFSET_BITS=64   -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=implicit-function-declaration  -fPIC -I/home/aaron/.rvm/rubies/ruby-1.9.3-p0/include/ruby-1.9.1 -I/home/aaron/.rvm/rubies/ruby-1.9.3-p0/include/ruby-1.9.1/i686-linux -c -o ext/avoutput.o ext/avoutput.cc
ext/avoutput.cc: In constructor ‘AVOutput::AVOutput(const string&, int, int, int, int, int, int, int, CodecID, int, int, int, CodecID)’:
ext/avoutput.cc:45:52: error: ‘guess_format’ was not declared in this scope
ext/avoutput.cc:65:21: error: ‘CODEC_TYPE_VIDEO’ was not declared in this scope
ext/avoutput.cc:82:23: error: ‘CODEC_TYPE_AUDIO’ was not declared in this scope
ext/avoutput.cc:89:5: warning: ‘int av_set_parameters(AVFormatContext*, AVFormatParameters*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1336) [-Wdeprecated-declarations]
ext/avoutput.cc:89:5: warning: ‘int av_set_parameters(AVFormatContext*, AVFormatParameters*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1336) [-Wdeprecated-declarations]
ext/avoutput.cc:120:7: warning: ‘int url_fopen(AVIOContext**, const char*, int)’ is deprecated (declared at /usr/include/libavformat/avio.h:278) [-Wdeprecated-declarations]
ext/avoutput.cc:120:7: warning: ‘int url_fopen(AVIOContext**, const char*, int)’ is deprecated (declared at /usr/include/libavformat/avio.h:278) [-Wdeprecated-declarations]
ext/avoutput.cc:124:5: warning: ‘int av_write_header(AVFormatContext*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1394) [-Wdeprecated-declarations]
ext/avoutput.cc:124:5: warning: ‘int av_write_header(AVFormatContext*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1394) [-Wdeprecated-declarations]
ext/avoutput.cc: In member function ‘void AVOutput::close()’:
ext/avoutput.cc:194:7: warning: ‘int url_fclose(AVIOContext*)’ is deprecated (declared at /usr/include/libavformat/avio.h:279) [-Wdeprecated-declarations]
ext/avoutput.cc:194:28: warning: ‘int url_fclose(AVIOContext*)’ is deprecated (declared at /usr/include/libavformat/avio.h:279) [-Wdeprecated-declarations]
ext/avoutput.cc: In member function ‘void AVOutput::writeVideo(FramePtr)’:
ext/avoutput.cc:272:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
ext/avoutput.cc:276:25: error: ‘PKT_FLAG_KEY’ was not declared in this scope
ext/avoutput.cc: In member function ‘void AVOutput::writeAudio(SequencePtr)’:
ext/avoutput.cc:303:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
ext/avoutput.cc:306:21: error: ‘PKT_FLAG_KEY’ was not declared in this scope
ext/avoutput.cc: In static member function ‘static VALUE AVOutput::registerRubyClass(VALUE)’:
ext/avoutput.cc:448:20: error: ‘CODEC_ID_XVID’ was not declared in this scope
rake aborted!
Command failed with status (1): [g++ -DNDEBUG -DHAVE_CONFIG_H -D__STDC_CONS...]
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `call'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `sh'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `sh'
/home/aaron/code/gems/hornetseye-ffmpeg/Rakefile:263:in `block in <top (required)>'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:203:in `call'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:203:in `block in execute'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/aaron/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/aaron/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/aaron/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/aaron/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in `load'
/home/aaron/.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in `<main>'
Tasks: TOP => default => all => ext/hornetseye_ffmpeg.so => ext/avoutput.o

Thanks for any help, and best of luck!

**Comment by wedesoft** [comment]
The compilation issues have been fixed in the meantime. Some other issues remain open though.
