### ISSUE TITLE
hornetseye-ffmpeg on MacOS

### ISSUE THREAD

**Issue by niuage** [wedesoft/hornetseye-ffmpeg#8]
Hi,

This gem doesn't seem very active anymore, but I was hoping to be able to use it on Mac.

I'm having these issues:

![rlreader_ _robbout_robs-macbook-pro-2_ _-zsh_ _199x57](https://user-images.githubusercontent.com/208622/51488042-85379380-1d72-11e9-9848-396fb2b3e66e.png)

Can I install an older version of ffmpeg? What's the latest supported version?

**Comment by wedesoft** [comment]
Hi, sorry but I haven't updated the Gem to work with a recent version of FFmpeg. I also don't know the last supported version number, sorry about that.

**Comment by niuage** [comment]
Thanks for answering. I'm now using ffmpeg directly and it's working fine for my use case actually.
